# Generated by Django 5.1.2 on 2024-11-18 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('apellidos', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=8)),
                ('genero', models.CharField(max_length=1)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_aprobacion', models.DateTimeField()),
                ('fecha_vencimiento', models.DateTimeField()),
                ('tasa_interes', models.DecimalField(decimal_places=2, help_text='Porcentaje de la tasa de interés', max_digits=5)),
                ('estado_credito', models.CharField(choices=[('VIGENTE', 'Vigente'), ('TERMINADO', 'Terminado'), ('INCUMPLIDO', 'Incumplido')], max_length=150)),
                ('fk_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prestamos.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.TextField()),
                ('ocupacion', models.CharField(max_length=150)),
                ('fecha_inicio_ocupacion', models.DateField()),
                ('total_ingresos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_ocupacion', models.CharField(max_length=150)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('fk_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prestamos.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='PlanPagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250)),
                ('cantidad_pagos', models.DecimalField(decimal_places=0, max_digits=5)),
                ('inicio_pago', models.DateField()),
                ('fin_pago', models.DateField()),
                ('fk_credito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prestamos.credito')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateField()),
                ('fecha_pago', models.DateField()),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_pago', models.CharField(default='Pendiente', max_length=50)),
                ('fk_plan_pagos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prestamos.planpagos')),
            ],
        ),
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(max_length=50)),
                ('fecha_resepcion', models.DateTimeField(auto_now_add=True)),
                ('fecha_devolucion', models.DateTimeField(null=True)),
                ('fk_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prestamos.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='credito',
            name='fk_prenda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prestamos.prenda'),
        ),
        migrations.CreateModel(
            name='SolicitudCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_solicitud', models.DateTimeField()),
                ('fecha_aprobacion', models.DateTimeField()),
                ('tasa_interes', models.DecimalField(decimal_places=0, max_digits=10)),
                ('estado_solicitud', models.CharField(choices=[('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('PENDIENTE', 'Pendiente')], max_length=50)),
                ('fk_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prestamos.cliente')),
                ('fk_prenda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prestamos.prenda')),
            ],
        ),
        migrations.AddField(
            model_name='credito',
            name='fk_solicitud_credito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prestamos.solicitudcredito'),
        ),
    ]
