# Generated by Django 5.1.2 on 2024-10-24 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('apellidos', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=8)),
                ('genero', models.CharField(max_length=1)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.TextField()),
                ('ocupacion', models.CharField(max_length=150)),
                ('fecha_inicio_ocupacion', models.DateField()),
                ('total_ingresos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_ocupacion', models.CharField(max_length=150)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('fk_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prestamos.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(max_length=50)),
                ('fecha_resepcion', models.DateTimeField(auto_now_add=True)),
                ('fecha_devolucion', models.DateTimeField(null=True)),
                ('fk_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prestamos.cliente')),
            ],
        ),
    ]
